# Generated by Django 4.2.7 on 2024-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
