# Generated by Django 4.2.7 on 2024-01-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_quizscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='quiz_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
