# Generated by Django 4.2.7 on 2024-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizscore_quiz_count_alter_quizscore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='quiz_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
